##This code is used to generate PCAs for QUAC clustering analysis
#This code uses data frames that have been generated by relatedness reduction -
#where individuals that are related by 25% are reduced to 1 representative 
#individual as this can bias genetic clustering analyses. This analysis
#performs PCAs with several population combinations - all wild pops,
#wild pops with all garden individuals, and finally wild and garden populations
#grouped just by pop types to assess how individuals clustered.

#####################
#     Libraries     #
#####################

library(adegenet)
library(diveRsity)
library(ggplot2)
library(randomcoloR)

#########################
#     Load in Files     #
#########################
#set working directory
setwd("../../Data_Files")

#data file lists 
sp_genind_list <- list.files(path = "Adegenet_Files", pattern = "clean.gen")
sp_df_list <- list.files(path = "Data_Frames", pattern = "clean_df.csv")

#list of scenarios 
scenario_list <- c("QUAC_wK", "QUAC_woK", "ZAIN_og", "ZAIN_rebinned")

#pop list 
pop_list <- list(c(1:17), c(1:17), c(1:10), c(1:10),
                 c(18:22), c(18:21), c(11:35), c(11:35))

###############
#     PCA     #
###############

#loop to write garden and wild comparison PCA 
for(sp in 1:length(scenario_list)){
  
  ##code to reorganize genind objects into "garden" and "wild" genind objects
  #load genepop files as genind objects 
  sp_genind_temp <- read.genepop(paste0("Adegenet_Files/",sp_genind_list[[sp]]), ncode = 3)
  
  #separate garden individuals into one population 
  sp_garden_genind <- repool(seppop(sp_genind_temp)[pop_list[[sp]]])
  #rename populations
  levels(sp_garden_genind@pop) <- rep("Garden", length(pop_list[[sp]]))
  
  #separate wild individuals and garden individuals 
  sp_wild_genind <- repool(seppop(sp_genind_temp)[pop_list[[sp+4]]])
  #rename to wild only 
  levels(sp_wild_genind@pop) <- rep("Wild", length(pop_list[[sp+4]]))
  
  #combine into one genind object 
  sp_genind_rp <- repool(sp_garden_genind, sp_wild_genind)
    
  #create tab object for genind 
  sp_tab <- tab(sp_genind_rp, freq=TRUE, NA.method = "mean")
  
  #run PCA
  sp_PCA <- dudi.pca(sp_tab, scale = FALSE, nf = 2, scannf = FALSE)
  
  #create PCA data frame 
  sp_PCA_df_temp <- as.data.frame(cbind(as.numeric(sp_PCA$li$Axis1), 
                                        as.numeric(sp_PCA$li$Axis2), 
                                        c(rep("Garden", as.numeric(table(sp_garden_genind@pop))),
                                          rep("Wild", as.numeric(table(sp_wild_genind@pop))))))
  colnames(sp_PCA_df_temp) <- c("Axis1","Axis2","Pop")
  
  #calculate % variation explained by axis 
  sp_pc1 <- signif(((sp_PCA$eig[1])/sum(sp_PCA$eig))*100, 3)
  sp_pc2 <- signif(((sp_PCA$eig[2])/sum(sp_PCA$eig))*100, 3)
  
  #plot PCA
  pdf(paste0("../Analyses/Results/Clustering/PCA/", scenario_list[[sp]], "_garden_wild_PCA.pdf"),width = 10, height = 8)
  
  print(ggplot(sp_PCA_df_temp, aes(as.numeric(Axis1), as.numeric(Axis2), col = Pop)) + geom_point() + 
          stat_ellipse() +
          xlab(paste0("PC1 (", sp_pc1, "%)")) +
          ylab(paste0("PC2 (", sp_pc2, "%)")) + 
          theme_bw() +  
          scale_color_manual(values=hcl.colors(n = length(unique(sp_PCA_df_temp$Pop)), palette = "viridis")))
  dev.off()
  
}

#loop to generate all wild pops PCA 
for(sp in 1:length(scenario_list)){
  
  #load in genind object 
  sp_genind_temp <- read.genepop(paste0("Adegenet_Files/", sp_genind_list[[sp]]), ncode = 3)
  
  #load data frame 
  sp_df <- read.csv(paste0("Data_Frames/", sp_df_list[[sp]]))
  
  #separate wild individuals 
  sp_wild_genind <- repool(seppop(sp_genind_temp)[pop_list[[sp+4]]])

  #create tab object for genind 
  sp_tab <- tab(sp_wild_genind, freq=TRUE, NA.method="mean")
  
  #run PCA
  sp_PCA <- dudi.pca(sp_tab, scale = FALSE, nf = 2, scannf = FALSE)
  
  #create PCA data frame 
  sp_PCA_df_temp <- as.data.frame(cbind(as.numeric(sp_PCA$li$Axis1), 
                                        as.numeric(sp_PCA$li$Axis2),
                                        sp_df[,2]))
  colnames(sp_PCA_df_temp) <- c("Axis1","Axis2","Pop")
  
  #calculate % variation explained by axis 
  sp_pc1 <- signif(((sp_PCA$eig[1])/sum(sp_PCA$eig))*100, 3)
  sp_pc2 <- signif(((sp_PCA$eig[2])/sum(sp_PCA$eig))*100, 3)
  
  #plot PCA
  pdf(paste0("../Analyses/Results/Clustering/PCA/", scenario_list[[sp]], "_wildpop_PCA.pdf"),width = 10, height = 8)
  
  print(ggplot(sp_PCA_df_temp, aes(as.numeric(Axis1), as.numeric(Axis2), col = Pop)) + geom_point() + 
          stat_ellipse() +
          xlab(paste0("PC1 (", sp_pc1, "%)")) +
          ylab(paste0("PC2 (", sp_pc2, "%)")) + 
          theme_bw() +  
          scale_color_manual(values=randomColor(count = length(unique(sp_PCA_df_temp$Pop)))))
  dev.off()
  
}

#loop to generate garden vs. all wild pops PCA 
for(sp in 1:length(scenario_list)){
  
  #load in genind object 
  sp_genind_temp <- read.genepop(paste0("Adegenet_Files/", sp_genind_list[[sp]]), ncode = 3)

  #load in species data frame
  sp_df <- read.csv(paste0("Data_Frames/", sp_df_list[[sp]]))
  
  #separate garden individuals into one population 
  sp_garden_genind <- repool(seppop(sp_genind_temp)[pop_list[[sp]]])
  #rename populations
  levels(sp_garden_genind@pop) <- rep("Garden", length(pop_list[[sp]]))
  
  #separate wild individuals 
  sp_wild_genind <- repool(seppop(sp_genind_temp)[pop_list[[sp+4]]])
  
  #name pops by wild pop 
  levels(sp_wild_genind@pop) <- unique(sp_df[,2])
    
  #combine objects into one genind object from wild and garden processing
  sp_garden_allwildpop_genind <- repool(sp_garden_genind, sp_wild_genind)
  
  #create tab object for genind 
  sp_tab <- tab(sp_garden_allwildpop_genind, freq=TRUE, NA.method="mean")
  
  #run PCA
  sp_PCA <- dudi.pca(sp_tab, scale = FALSE, nf = 2, scannf = FALSE)
  
  #create PCA data frame 
  sp_PCA_df_temp <- as.data.frame(cbind(as.numeric(sp_PCA$li$Axis1), 
                                        as.numeric(sp_PCA$li$Axis2), 
                                        sp_df[,2]))
  colnames(sp_PCA_df_temp) <- c("Axis1","Axis2","Pop")
  
  #calculate % variation explained by axis 
  sp_pc1 <- signif(((sp_PCA$eig[1])/sum(sp_PCA$eig))*100, 3)
  sp_pc2 <- signif(((sp_PCA$eig[2])/sum(sp_PCA$eig))*100, 3)
  
  #plot PCA
  pdf(paste0("../Analyses/Results/Clustering/PCA/", scenario_list[[sp]], "_garden_allwildpop_PCA.pdf"),width = 10, height = 8)
  
  print(ggplot(sp_PCA_df_temp, aes(as.numeric(Axis1), as.numeric(Axis2), col = Pop)) + geom_point() + 
          stat_ellipse() +
          xlab(paste0("PC1 (", sp_pc1, "%)")) +
          ylab(paste0("PC2 (", sp_pc2, "%)")) + 
          theme_bw() +  
          scale_color_manual(values=hcl.colors(n = length(unique(sp_PCA_df_temp$Pop)), palette = "viridis")))
  dev.off()
  
  
}

##run PCA on just Quercus acerifolia individuals 
#read in genepop files as a genind object
QUAC_wK_gen <- read.genepop("Adegenet_Files/QUAC_allpop_clean.gen", ncode = 3)

QUAC_wk_wild_gen <- repool(seppop(QUAC_wK_gen)[18:22])

#read in data frame 
QUAC_wk_df <- read.csv("Data_Frames/QUAC_allpop_clean_df.csv")

QUAC_wk_wild_df <- QUAC_wk_df[QUAC_wk_df$Garden_Wild == "Wild",]

#name rows in the genind object 
rownames(QUAC_wk_wild_gen@tab) <- QUAC_wk_wild_df[,1]
#name pops
levels(QUAC_wk_wild_gen@pop) <- unique(QUAC_wk_wild_df[,2])

#create tab object for genind 
QUAC_wk_wild_tab <- tab(QUAC_wk_wild_gen, freq=TRUE, NA.method="mean")

#run PCA
QUAC_wk_wild_PCA <- dudi.pca(QUAC_wk_wild_tab, scale = FALSE, nf = 2, scannf = FALSE)

#create PCA data frame 
QUAC_wk_wild_PCA_df <- as.data.frame(cbind(as.numeric(QUAC_wk_wild_PCA$li$Axis1), 
                                      as.numeric(QUAC_wk_wild_PCA$li$Axis2), 
                                      QUAC_wk_wild_df[,2]))
colnames(QUAC_wk_wild_PCA_df) <- c("Axis1","Axis2","Pop")

#calculate % variation explained by axis 
QUAC_wild_pc1 <- signif(((QUAC_wk_wild_PCA$eig[1])/sum(QUAC_wk_wild_PCA$eig))*100, 3)
QUAC_wild_pc2 <- signif(((QUAC_wk_wild_PCA$eig[2])/sum(QUAC_wk_wild_PCA$eig))*100, 3)

#plot PCA
pdf("../Analyses/Results/Clustering/QUAC_allwildpop_PCA.pdf", width = 10, height = 8)

 ggplot(QUAC_wk_wild_PCA_df, aes(as.numeric(Axis1), as.numeric(Axis2), col = Pop)) + geom_point() + 
        stat_ellipse() +
        xlab(paste0("PC1 (", QUAC_wild_pc1, "%)")) +
        ylab(paste0("PC2 (", QUAC_wild_pc2, "%)")) + 
        theme_bw() +  
        scale_color_manual(values=hcl.colors(n = length(unique(QUAC_wk_wild_PCA_df$Pop)), palette = "viridis"))
  

dev.off()

#
setwd("C:/Users/eschumacher/Documents/GitHub/GCC_QUAC_ZAIN/Data_Files")

#load genind object
ZAIN_rebinned_genind <- read.genepop("Adegenet_Files/ZAIN_rebinned_allpop_clean.gen", ncode = 3)

#load data frame 
ZAIN_rebinned_df <- read.csv("Data_Frames/ZAIN_rebinned_allpop_clean_df.csv")

#reorg 
rownames(ZAIN_rebinned_genind@tab) <- ZAIN_rebinned_df$Sample.Name
levels(ZAIN_rebinned_genind@pop) <- unique(ZAIN_rebinned_df$Pop)
wild_pops <- ZAIN_rebinned_df[ZAIN_rebinned_df$Garden_Wild == "Wild",]$Pop

#save just wild pops 
ZAIN_wild_rebinned_genind <- repool(seppop(ZAIN_rebinned_genind)[11:35])

#create tab object for genind 
ZAIN_wild_rebinned_tab <- tab(ZAIN_wild_rebinned_genind, freq=TRUE, NA.method="mean")

#run PCA
ZAIN_PCA <- dudi.pca(ZAIN_wild_rebinned_tab, scale = FALSE, nf = 2, scannf = FALSE)

#create PCA data frame 
ZAIN_PCA_df <- as.data.frame(cbind(as.numeric(ZAIN_PCA$li$Axis1), 
                                   as.numeric(ZAIN_PCA$li$Axis2), wild_pops))

colnames(ZAIN_PCA_df) <- c("Axis1","Axis2","Pop")

#calculate % variation explained by axis 
ZAIN_pc1 <- signif(((ZAIN_PCA$eig[1])/sum(ZAIN_PCA$eig))*100, 3)
ZAIN_pc2 <- signif(((ZAIN_PCA$eig[2])/sum(ZAIN_PCA$eig))*100, 3)

##replace colors in the PCA document 
for(1:nrow(ZAIN_PCA_df)){
  
  #repalce names 
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFB",][,3] <- "Bronson"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFBP1",][,3] <- "Bulow1"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFBP2",][,3] <- "Bulow2"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFCC",][,3] <- "Cayo Costa"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFCNS",][,3] <- "Canaveral"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZCF",][,3] <- "Chapman Field"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFCR",][,3] <- "Crystal River"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFENP",][,3] <- "Everglades"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFFDSP",][,3] <- "Faver-Dykes"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFI",][,3] <- "Ichetucknee"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFK",][,3] <- "Koreshan"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFLB",][,3] <- "Broward"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFLTI",][,3] <- "Little Talbot Island"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFONF1",][,3] <- "Ocala1"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFONF2",][,3] <- "Ocala2"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFO",][,3] <- "Oscar Scherer"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFBP",][,3] <- "Palm Beach"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFSW1",][,3] <- "Suwannee1"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFSW2",][,3] <- "Suwannee2"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFTS",][,3] <- "Tide Swamp"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFTSP1",][,3] <- "Tomoka1"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFTSP2",][,3] <- "Tomoka2"
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == "ZFWB",][,3] <- "Werner-Boyce"
  
}


umbrosa_pops <- c("Bulow1", "Bulow2","Canaveral",
                  "Faver-Dykes", "Little Talbot Island",
                  "Ocala1", "Ocala2", "Tomoka1", "Tomoka2")

for(p in 1:length(umbrosa_pops)){
  
  ZAIN_PCA_df[ZAIN_PCA_df$Pop == umbrosa_pops[[p]],]$variety <- "umbrosa"
  
}

pdf("../Analyses/Results/Clustering/PCA/ZAIN_wildpop_PCA.pdf", width = 8,
    height = 6)
ggplot(ZAIN_PCA_df, aes(as.numeric(Axis1), as.numeric(Axis2), col = variety)) + 
  geom_vline(xintercept=0,lwd=1,colour="black") +
  geom_hline(yintercept=0,lwd=1,colour="black") +
  geom_point(size = 3) + 
  xlab(paste0("PC1 (", ZAIN_pc1, "%)")) +
  ylab(paste0("PC2 (", ZAIN_pc2, "%)")) + 
  theme_bw() +  
  scale_color_manual(values=c("dodgerblue","cadetblue3"))
dev.off()


