##This script details the relatedness analyses performed on Quercus acerifolia 
#and Zamia integrifolia (referred to as QUAC and ZAIN in this script for brevity). 
#This file first cleans and assesss the numbers of individuals predicted to be 
#half and full siblings within garden and wild populations generated by Demerelate
#and then compares this to the individual numbers predicted by the program
#Spagedi. Spagedi files are generated externally to R and so we use the output
#files for this step, but Demerelate predicted relatedness levels are predicted
#using the R package Demerelate. 

#########################
#        Libraries      #
#########################

library(Demerelate)
library(parallel)

#######################
#     Load Files      #     
#######################
#set working directory to load in data files 
setwd("../../Data_Files")

#list out data files for demerelate relatedness analysis
sp_rel_df <- list.files(path = "CSV_Files/", pattern = "clean_df")

#create list of files that have the kinship information 
sp_spagedi_out_df <- list.files(path = "../Analyses/Results/Relatedness/", pattern = "df")

#create scenario list 
scenario_list <- c("QUAC_wK", "QUAC_woK", "ZAIN_og", "ZAIN_rebinned")

#number of individuals for each population 
pop_numbers <- c(277, 277, 172, 172, 382, 382, 751, 751)

###################################
#     Demerelate relatedness      #
###################################
#create lists to store results in 
rel_df_list <- list()
rel_garden_df_list <- list()
rel_wild_df_list <- list()

#load in relatedness data files
for(r in 1:length(sp_rel_df)) rel_df_list[[r]] <- read.csv(paste0("CSV_Files/",sp_rel_df[[r]])) 
#prep data files for relatedness analysis in Demerelate - garden
for(g in 1:length(rel_df_list)) rel_garden_df_list[[g]] <- rel_df_list[[g]][,-2] 
#prep data files for relatedness analysis in Demerelate - wild
for(w in 1:length(rel_df_list)) rel_wild_df_list[[w]] <- rel_df_list[[w]][rel_df_list[[w]][,3] == "Wild",-3]

##run relatedness analysis using Demerelate
#use parallel functions
#Calculate the number of cores
cores <- detectCores() - 1
#Initiate cluster
cl <- makeCluster(cores)

#run relatedness analysis for garden and wild pop types 
sp_garden_rel <- parLapply(cl,rel_garden_df_list, Demerelate, tab.dist = "NA", object = TRUE, value = "loiselle")
sp_wild_rel <- parLapply(cl,rel_wild_df_list, Demerelate, tab.dist = "NA", object = TRUE, value = "loiselle")

#matrix to store relatedness results
sp_garden_rel_df <- matrix(nrow = 2, ncol = length(sp_garden_rel))
sp_wild_rel_df <- matrix(nrow = 2, ncol = length(sp_wild_rel))

##Garden demerelate analysis
#create lists 
sp_deme_garden_halfsib_list <- list()
sp_deme_garden_fullsib_list <- list()
sp_deme_garden_halfsib_per_list <- list()
sp_deme_garden_fullsib_per_list <- list()

#loop to calculate demerelate halfsibs and full sibs in gardens 
for(g in 1:length(sp_garden_rel)){
  
  #calculate list of individuals with a half sib in the sample
  sp_deme_garden_rel_df <- as.data.frame(sp_garden_rel[[g]]$Empirical_Relatedness$Garden) 
  
  sp_deme_garden_rel_df$halfsib <- NA
  sp_deme_garden_rel_df$fullsib <- NA
  
  #calculate half-sib levels 
  sp_deme_garden_rel_df$halfsib <- sp_deme_garden_rel_df[,1] > 0.125
  
  #calculate full sib levels 
  sp_deme_garden_rel_df$fullsib <- sp_deme_garden_rel_df[,1] > 0.25
  
  #create a column for individual names 
  sp_deme_garden_rel_df$Ind1 <- gsub("_.*","", rownames(sp_deme_garden_rel_df))
  sp_deme_garden_rel_df$Ind2 <- gsub("^.*\\_","", rownames(sp_deme_garden_rel_df))
  
  #create a list of numbers of individuals with a half or full sib in the sample
  sp_deme_garden_halfsib_list[[g]] <- length(unique(sp_deme_garden_rel_df[sp_deme_garden_rel_df$halfsib == TRUE,]$Ind1))
  sp_deme_garden_fullsib_list[[g]] <- length(unique(sp_deme_garden_rel_df[sp_deme_garden_rel_df$fullsib == TRUE,]$Ind1))
  
  
  #create a list of the percent of individuals with a half or full sib in the sample
  sp_deme_garden_halfsib_per_list[[g]] <- (length(unique(sp_deme_garden_rel_df[sp_deme_garden_rel_df$halfsib == TRUE,]$Ind1))/length(rel_garden_df_list[[g]][rel_garden_df_list[[g]]$Garden_Wild == "Garden",][,1]))*100
  sp_deme_garden_fullsib_per_list[[g]] <- (length(unique(sp_deme_garden_rel_df[sp_deme_garden_rel_df$fullsib == TRUE,]$Ind1))/length(rel_garden_df_list[[g]][rel_garden_df_list[[g]]$Garden_Wild == "Garden",][,1]))*100
  
}

#code for reporting these stats 
#create output matrix
sp_garden_deme_output_df <- matrix(nrow = 2, ncol = length(sp_deme_garden_halfsib_list))

#loop to make the data frame
for(sp in 1:length(sp_deme_garden_halfsib_per_list)){
  
  #half sibling row with % half sibs and # of individuals with a half sib
  sp_garden_deme_output_df[1,sp] <- paste0(signif(as.numeric(sp_deme_garden_halfsib_per_list[[sp]]), 3), "% (", sp_deme_garden_halfsib_list[[sp]], ")")
  
  #full sib percent and number 
  sp_garden_deme_output_df[2,sp] <- paste0(signif(as.numeric(sp_deme_garden_fullsib_per_list[[sp]]), 3), "% (", sp_deme_garden_fullsib_list[[sp]], ")")
  
}

#name rows and columns 
rownames(sp_garden_deme_output_df) <- c("half_sibs","full_sibs")
colnames(sp_garden_deme_output_df) <- scenario_list
#write out data frame 
write.csv(sp_garden_deme_output_df, "../Analyses/Results/Relatedness/sp_garden_deme_output_df.csv")

##Wild demerelate relatedness analysis

#create lists
sp_deme_wild_rel_df <- list()
sp_deme_wild_halfsib_list <- list()
sp_deme_wild_fullsib_list <- list()
sp_deme_wild_halfsib_per_list <- list()
sp_deme_wild_fullsib_per_list <- list()

#loop to calculate demerelate half and full sibs in wild pops 
for(w in 1:length(sp_wild_rel)){
  
  #create data frame 
  sp_deme_wild_df <- sp_wild_rel[[w]]
  
  #create a variable for the # of wild pops 
  sp_wild_pop_num <- length(sp_wild_rel[[w]]$Empirical_Relatedness)
  
  #save relatedness results as data frames
  for(rel in 1:sp_wild_pop_num){
    
    sp_deme_wild_rel_df[[rel]] <- as.data.frame(sp_deme_wild_df$Empirical_Relatedness[rel])
    
    #name column to allow for rbind to work 
    colnames(sp_deme_wild_rel_df[[rel]]) <- c("Rel_Coeff")
  }
  
  #bind data frames together 
  sp_deme_allwildpop_df <- do.call(rbind,sp_deme_wild_rel_df)
  
  #create column for storing relatedness info 
  sp_deme_allwildpop_df$halfsib <- NA
  sp_deme_allwildpop_df$fullsib <- NA
  
  #mark what are not halfsibs 
  sp_deme_allwildpop_df$halfsib <- sp_deme_allwildpop_df[,1] > 0.125
  
  #mark full sibs 
  sp_deme_allwildpop_df$fullsib <- sp_deme_allwildpop_df[,1] > 0.25
  
  #create a column for individual names 
  sp_deme_allwildpop_df$Ind1 <- gsub("_.*","", rownames(sp_deme_allwildpop_df))
  sp_deme_allwildpop_df$Ind2 <- gsub("^.*\\_","", rownames(sp_deme_allwildpop_df))
  
  #create a list of numbers of individuals with a half or full sib in the sample
  sp_deme_wild_halfsib_list[[w]] <- length(unique(sp_deme_allwildpop_df[sp_deme_allwildpop_df$halfsib == TRUE,]$Ind1))
  v[[w]] <- length(unique(sp_deme_allwildpop_df[sp_deme_allwildpop_df$fullsib == TRUE,]$Ind1))
  
  
  #create a list of the percent of individuals with a half or full sib in the sample
  sp_deme_wild_halfsib_per_list[[w]] <- (length(unique(sp_deme_allwildpop_df[sp_deme_allwildpop_df$halfsib == TRUE,]$Ind1))/length(rel_wild_df_list[[w]][,1]))*100
  sp_deme_wild_fullsib_per_list[[w]] <- (length(unique(sp_deme_allwildpop_df[sp_deme_allwildpop_df$fullsib == TRUE,]$Ind1))/length(rel_wild_df_list[[w]][,1]))*100
  
}

##code for reporting these stats 
#create output matrix
sp_wild_deme_output_df <- matrix(nrow = 2, ncol = length(sp_deme_wild_halfsib_list))

#loop to make the data frame
for(sp in 1:length(sp_deme_wild_halfsib_list)){
  
  #half sibling row with % half sibs and # of individuals with a half sib
  sp_wild_deme_output_df[1,sp] <- paste0(signif(as.numeric(sp_deme_wild_halfsib_per_list[[sp]]), 3), "% (", sp_deme_wild_halfsib_list[[sp]], ")")
  
  #full sib percent and number 
  sp_wild_deme_output_df[2,sp] <- paste0(signif(as.numeric(sp_deme_wild_fullsib_per_list[[sp]]), 3), "% (", sp_deme_wild_fullsib_list[[sp]], ")")
  
}

#name rows and columns 
rownames(sp_wild_deme_output_df) <- c("half_sibs", "full_sibs")
colnames(sp_wild_deme_output_df) <- scenario_list

#write out results
write.csv(sp_wild_deme_output_df, "../Analyses/Results/Relatedness/sp_wild_deme_output_df.csv")

###############################
#     Spagedi relatedness     #
###############################

#create list to stores results 
sp_halfsib_list <- list()
sp_fullsib_list <- list()

sp_halfsib_percent_list <- list()
sp_fullsib_percent_list <- list()

#now use a loop to output the number of related ind 
for(rel in 1:length(spagedi_df)){
  
  #first, read in CSV files 
  sp_df <- read.csv(paste0("../Analyses/Results/Relatedness/",spagedi_df[[rel]]))
  
  #next, for each data frame, remove the row with the text "inbreeding coef"
  #this is a line that compares each ind to itself
  sp_df2 <- sp_df[!(sp_df$Dist == "inbreeding coef"),]
  
  ##add columns for sibling levels 
  #half-sib
  sp_df2$half_sib <- NA
  sp_df2$full_sib <- NA
  
  #calculate half-sib levels 
  sp_df2$halfsib <- sp_df2$Rel_Coeff > 0.125
  
  #calculate full sib levels 
  sp_df2$fullsib <- sp_df2$Rel_Coeff > 0.25
  
  #create a list of the percent of individuals with a half or full sib in the sample
  sp_halfsib_list[[rel]] <- length(unique(sp_df2[sp_df2$halfsib == TRUE,][,1]))
  sp_fullsib_list[[rel]] <- length(unique(sp_df2[sp_df2$fullsib == TRUE,][,1]))
  
  #create a list of the percent of individuals with a half or full sib in the sample
  sp_halfsib_percent_list[[rel]] <- (length(unique(sp_df2[sp_df2$halfsib == TRUE,][,1]))/pop_numbers[[rel]])*100
  sp_fullsib_percent_list[[rel]] <- (length(unique(sp_df2[sp_df2$fullsib == TRUE,][,1]))/pop_numbers[[rel]])*100
  
  
}

##code for reporting these stats 
#create output matrix
sp_spagedi_output_df <- matrix(nrow = 2, ncol = length(sp_halfsib_list))

#loop to make the data frame
for(sp in 1:length(sp_halfsib_percent_list)){
  
  #half sibling row with % half sibs and # of individuals with a half sib
  sp_spagedi_output_df[1,sp] <- paste0(signif(as.numeric(sp_halfsib_percent_list[[sp]]), 3), "% (", sp_halfsib_list[[sp]], ")")
  
  #full sib percent and number 
  sp_spagedi_output_df[2,sp] <- paste0(signif(as.numeric(sp_fullsib_percent_list[[sp]]), 3), "% (", sp_fullsib_list[[sp]], ")")
  
}

#name rows and columns 
colnames(sp_spagedi_output_df) <- c("QUAC_garden_sample", "QUAC_garden_whole", "QUAC_wild_sample",
                          "QUAC_wild_whole", "ZAIN_garden_sample", "ZAIN_garden_whole",
                          "ZAIN_wild_sample", "ZAIN_wild_whole")

rownames(sp_spagedi_output_df) <- c("half_sibs","full_sibs")

#write out data file
write.csv(sp_spagedi_output_df, "../Analyses/Results/Relatedness/sp_spagedi_output_df.csv")

sessionInfo()

#########################
#   Load Data Files     #
#########################
#set working directory to load in data files 
setwd("../../Data_Files")

#load relatedness data frame for relatedness analysis 
sp_df <- list.files(path = "CSV_Files", pattern = "allpop_df.csv$")

#create scenario list 
scenario_list <- c("QUAC_wK", "QUAC_woK", "ZAIN_og", "ZAIN_rebinned")

#function to output the % of sibs in all garden pops 
fullsib_loiselle_rel_fun <- function(x){
  
  #clean front characters
  fullsib_clean_front <- gsub("^.*\\.","", x)
  
  #clean the duplicate name 
  fullsib_clean_back <- gsub("^.*\\_","", fullsib_clean_front)
  
  #create list of unique individuals greater than and equal to full sib relatedness
  fullsib_list <- unique(fullsib_clean_back)
  
  #return the list of full sibs
  return(fullsib_list)
}

###################################
#     Demerelate Ref Pop Test     #
###################################

##first, load in one data file and run relatedness analysis to determine 
#how different population structures changes levels of relatedness 
#detected. 

#load in QUAC data file 
QUAC_rel_df <- read.csv("CSV_Files/QUAC_allpop_clean_df.csv")

##run relatedness analysis on different organizations of the data file
#list scenarios: 
##gwtog indicates the data file for relatedness has the wild and garden
#individuals combined in the data file
##gwsep has removed the garden or wild depending on the pop of interest
##labpopsep indicates that every population is separately named - all wild
#pops and gardens pops 
##labpopgr indicates all wild and garden individuals are grouped into
#metapopulations of just "wild" and "garden"
rel_scen <- c("gwtog_labpopsep_garden", "gwtog_labpopsep_wild", 
              "gwtog_labpopgr_garden", "gwtog_labpopgr_wild", 
              "gwsep_labpopsep_garden", "gwsep_labpopsep_wild",
              "gwsep_labpopgr_garden", "gwsep_labpopgr_wild")

#populations of gardens
garden_pops <- unique(QUAC_rel_df[QUAC_rel_df$Garden_Wild == "Garden",]$Pop)
wild_pops <- unique(QUAC_rel_df[QUAC_rel_df$Garden_Wild == "Wild",]$Pop)

#create matrix to store results 
rel_popstr_table <- matrix(nrow = length(rel_scen), 
                           ncol = 1)

#loop to calculate relatedness in different pop structures
for(r in 1:length(rel_scen)){
  
  #wild and garden together with pops labeled separately 
  if(r == 1|r == 2){
    
    #remove pop type column to run relatedness - wild and garden individuals grouped
    #into large metapopulations 
    QUAC_scen_rel_df <- QUAC_rel_df[,-3]
    
    #run relatedness analysis for garden and wild pop types 
    QUAC_relate_df <- Demerelate(QUAC_scen_rel_df, tab.dist = "NA", object = TRUE, value = "loiselle")
    
    #garden relatedness
    rel_popstr_table[1,1] <- 277 - length(fullsib_loiselle_rel_fun(names(which(unlist(QUAC_relate_df$Empirical_Relatedness[garden_pops]) > 0.25))))
    #wild relatedness
    rel_popstr_table[2,1] <- 172 - length(fullsib_loiselle_rel_fun(names(which(unlist(QUAC_relate_df$Empirical_Relatedness[wild_pops]) > 0.25))))
  }
  
  #wild and garden together with pops grouped by garden and wild 
  if(r == 3|r == 4){
    
    #remove separate garden and wild populations column  
    QUAC_scen_rel_df <- QUAC_rel_df[,-2]
    
    #run relatedness analysis for garden and wild pop types 
    QUAC_relate_df <- Demerelate(QUAC_scen_rel_df, tab.dist = "NA", object = TRUE, value = "loiselle")
    
    #garden relatedness
    rel_popstr_table[3,1] <- 277 - length(fullsib_loiselle_rel_fun(names(which(unlist(QUAC_relate_df$Empirical_Relatedness$Garden) > 0.25))))
    #wild relatedness
    rel_popstr_table[4,1] <- 172 - length(fullsib_loiselle_rel_fun(names(which(unlist(QUAC_relate_df$Empirical_Relatedness$Wild) > 0.25))))
    
  }
  
  #garden separate with pops separated 
  if(r == 5){
    
    QUAC_scen_rel_df <- QUAC_rel_df[QUAC_rel_df$Garden_Wild == "Garden",-3]
    
    #run relatedness analysis for garden and wild pop types 
    QUAC_relate_df <- Demerelate(QUAC_scen_rel_df, tab.dist = "NA", object = TRUE, value = "loiselle")
    
    #garden relatedness
    rel_popstr_table[5,1] <- 277 - length(fullsib_loiselle_rel_fun(names(which(unlist(QUAC_relate_df$Empirical_Relatedness[garden_pops]) > 0.25))))
    
  }
  
  #wild separate with pops separated
  if(r == 6){
    
    QUAC_scen_rel_df <- QUAC_rel_df[QUAC_rel_df$Garden_Wild == "Wild",-3]
    
    #run relatedness analysis for garden and wild pop types 
    QUAC_relate_df <- Demerelate(QUAC_scen_rel_df, tab.dist = "NA", object = TRUE, value = "loiselle")
    
    #garden relatedness
    rel_popstr_table[6,1] <- 172 - length(fullsib_loiselle_rel_fun(names(which(unlist(QUAC_relate_df$Empirical_Relatedness[wild_pops]) > 0.25))))
    
  }
  
  #garden populations pooled with just garden individuals 
  if(r == 7){
    
    #select only garden individuals and remove the sep pop labels
    QUAC_scen_rel_df <- QUAC_rel_df[QUAC_rel_df$Garden_Wild == "Garden",-2]
    
    #run relatedness analysis for garden and wild pop types 
    QUAC_relate_df <- Demerelate(QUAC_scen_rel_df, tab.dist = "NA", object = TRUE, value = "loiselle")
    
    #garden relatedness
    rel_popstr_table[7,1] <- 277 - length(fullsib_loiselle_rel_fun(names(which(unlist(QUAC_relate_df$Empirical_Relatedness$Garden) > 0.25))))
    
    
  }
  
  #wild populations pooled with just wild individuals 
  if(r == 8){
    
    #select only garden individuals and remove the sep pop labels
    QUAC_scen_rel_df <- QUAC_rel_df[QUAC_rel_df$Garden_Wild == "Wild", -2]
    
    #run relatedness analysis for garden and wild pop types 
    QUAC_relate_df <- Demerelate(QUAC_scen_rel_df, tab.dist = "NA", object = TRUE, value = "loiselle")
    
    #garden relatedness
    rel_popstr_table[8,1] <- 172 - length(fullsib_loiselle_rel_fun(names(which(unlist(QUAC_relate_df$Empirical_Relatedness$Wild) > 0.25))))
    
    
  }
  
}


##write out data table from the different pop structures analysis 
#name rows and columns 
rownames(rel_popstr_table) <- rel_scen
colnames(rel_popstr_table) <- c("non_halfsibs")
#write out table
write.csv(rel_popstr_table, "../Analyses/Results/Relatedness/rel_popstr_table.csv")

###################################
#     Relate Indicator Tests      #
###################################
##This area details the part of the script testing how if relatedness indicators
#identified different numbers of siblings within each pop type (garden or wild)

#list clean data frames 
sp_clean_df_list <- list.files(path = "CSV_Files", pattern = "clean_df.csv")

#relatedness lists for all analyses
sp_garden_relate_levels <- list()
sp_wild_relate_levels <- list()

#create a list of the relatedness tests 
relatedness_analyses_list <- c("loiselle", "wang", "ritland")

#save summary df 
relate_ind_fullsib_df <- matrix(nrow = length(scenario_list), ncol = 
                                  length(relatedness_analyses_list)*2)


###this analysis compares the number of full siblings determined by different
##relatedness indicators 
#this loop runs over the main data files 
for(sp in 1:length(scenario_list)){
  #this loop runs over different relatedness analyses
  for(relate in 1:length(relatedness_analyses_list)){
    #load in clean data frames to perform relatedness analysis on 
    sp_clean_temp_df <- read.csv(paste0("CSV_Files/",sp_clean_df_list[[sp]]))
    
    ##Run relate red code 
    #Garden
    sp_garden_clean_temp_df <- sp_clean_temp_df[,-2]
    
    #limit data frame by garden only 
    sp_garden_only_temp_df <- sp_garden_clean_temp_df[sp_garden_clean_temp_df[,2] == "Garden",]
    
    #run relatedness analysis 
    sp_garden_rel_df <- Demerelate(sp_garden_clean_temp_df, object = T, value = relatedness_analyses_list[[relate]])
    
    #save relatedness levels for each scenario to graph  
    sp_relate_levels[[sp]] <- sp_garden_rel_df$Empirical_Relatedness$Garden 
    
    #species full siblings 
    sp_garden_fullsib_list <- fullsib_loiselle_rel_fun(names(which(unlist(sp_garden_rel_df$Empirical_Relatedness$Garden) > 0.25)))
    
    #save in df 
    relate_ind_fullsib_df[sp, relate] <- paste0(signif(((length(sp_garden_fullsib_list))/length(sp_garden_only_temp_df[,1])),3)*100, "% (", 
                                                length(sp_garden_only_temp_df[,1]),")")
    
    
    ##Wild relatedness analysis 
    sp_wild_clean_temp_df <- sp_clean_temp_df[sp_clean_temp_df[,3] == "Wild",][,-3]
    
    #now run relatedness analysis 
    sp_wild_rel_df <- Demerelate(sp_wild_clean_temp_df, object = T, value = relatedness_analyses_list[[relate]])
    
    #limit by analysis halfsibs 
    sp_wild_fullsib_list <- fullsib_loiselle_rel_fun(names(which(unlist(sp_wild_rel_df$Empirical_Relatedness) > 0.25)))
    
    #number of ind removed 
    relate_ind_fullsib_df[sp, relate+3] <- paste0(signif(length(sp_wild_fullsib_list)/
                                                           length(sp_wild_clean_temp_df[,1])*100, 3), "% ",
                                                  "(", length(sp_wild_clean_temp_df[,1]) - length(sp_wild_fullsib_list), ")")
    
  }
}

#write out summary table 
rownames(relate_ind_fullsib_df) <- scenario_list
colnames(relate_ind_fullsib_df) <- rep(relatedness_analyses_list, 2)
write.csv(relate_ind_fullsib_df, "../Analyses/Results/Relatedness/relate_ind_fullsib_df.csv")


##making histograms of relatedness
#load in QUAC with Kessler data frame
QUAC_rel_df <- read.csv("CSV_Files/QUAC_allpop_clean_df.csv")

#matrix to store mean relatedness values for each relatedness analysis
#and p-values for comparisons
QUAC_rel_analysis_df <- matrix(nrow = 3, ncol = length(relatedness_analyses_list))

#loop to run relatedness analyses 
for(r in 1:length(relatedness_analyses_list)){
  
  ##Garden
  #create garden df
  sp_garden_temp_df <- QUAC_rel_df[,-2]
  
  #run relatedness analysis
  sp_garden_rel_df <- Demerelate(sp_garden_temp_df, object = T, value = relatedness_analyses_list[[r]])
  
  #generate histogram 
  pdf(paste0("../Analyses/Results/Relatedness/QUAC_garden_", relatedness_analyses_list[[r]],
             "_distribution.pdf"), width = 8, height = 8)
  hist(sp_garden_rel_df$Empirical_Relatedness$Garden, xlim = c(-1,1), ylim = c(0, 12000), 
       col = "darkseagreen1", xlab = paste0(relatedness_analyses_list[[r]]," Garden"),
       main = paste0("QUAC garden ",relatedness_analyses_list[[r]], " Distribution"))
  dev.off()
  
  ##Wild
  #limit to wild pops and remove pop type column 
  sp_wild_temp_df <- QUAC_rel_df[QUAC_rel_df$Garden_Wild == "Wild",-3]
  
  #run relatedness analysis
  sp_wild_rel_df <- Demerelate(sp_wild_temp_df, object = T, value = relatedness_analyses_list[[r]])
  
  #generate histogram 
  pdf(paste0("../Analyses/Results/Relatedness/QUAC_wild_", relatedness_analyses_list[[r]],
             "_distribution.pdf"), width = 8, height = 8)
  hist(as.numeric(unlist(sp_wild_rel_df$Empirical_Relatedness)), 
       xlim = c(-1,1), ylim = c(0, 1000), 
       col = "forestgreen", xlab = paste0(relatedness_analyses_list[[r]]," Wild"),
       main = paste0("QUAC Wild ", relatedness_analyses_list[[r]], " Distribution"))
  dev.off()
  
  #store garden means for each test
  QUAC_rel_analysis_df[1,r] <- mean(sp_garden_rel_df$Empirical_Relatedness$Garden)
  #store wild means for each test
  QUAC_rel_analysis_df[2,r] <- mean(as.numeric(unlist(sp_wild_rel_df$Empirical_Relatedness)))
  
  #compare distributions using nonparametric t-test 
  QUAC_rel_analysis_df[3,r] <- wilcox.test(sp_garden_rel_df$Empirical_Relatedness$Garden, 
                                           as.numeric(unlist(sp_wild_rel_df$Empirical_Relatedness)), exact = TRUE)[3]$p.value 
  
}

rownames(QUAC_rel_analysis_df) <- c("Garden", "Wild", "p-value")
colnames(QUAC_rel_analysis_df) <- relatedness_analyses_list

write.csv(QUAC_rel_analysis_df, "..Analyses/Results/Relatedness/QUAC_relatedness_analyses_sum_df.csv")

