##This script details the relatedness analyses performed on Quercus acerifolia 
#and Zamia integrifolia (referred to as QUAC and ZAIN in this script for brevity). 
#This file first cleans and assesss the numbers of individuals predicted to be 
#half and full siblings within garden and wild populations generated by Demerelate
#and then compares this to the individual numbers predicted by the program
#Spagedi. Spagedi files are generated externally to R and so we use the output
#files for this step, but Demerelate predicted relatedness levels are predicted
#using the R package Demerelate. 

#########################
#        Libraries      #
#########################

library(Demerelate)
library(parallel)

#######################
#     Load Files      #     
#######################
#set working directory to load in data files 
setwd("../../Data_Files")

#list out data files for demerelate relatedness analysis
sp_rel_df <- list.files(path = "Data_Frames/", pattern = "clean_df")

#create list of files that have the kinship information 
sp_spagedi_out_df <- list.files(path = "../Analyses/Results/Relatedness/", pattern = "df")

#create scenario list 
scenario_list <- c("QUAC_wK", "QUAC_woK", "ZAIN_og", "ZAIN_rebinned")

#number of individuals for each population 
pop_numbers <- c(277, 277, 172, 172, 382, 382, 751, 751)

###################################
#     Demerelate relatedness      #
###################################
#create lists to store results in 
rel_garden_df_list <- list()
rel_wild_df_list <- list()

#load in relatedness data files
for(r in 1:length(rel_df)) rel_df_list[[r]] <- read.csv(rel_df[[r]]) 
#prep data files for relatedness analysis in Demerelate - garden
for(g in 1:length(rel_df_list)) rel_garden_df_list[[g]] <- rel_df_list[[g]][,-2] 
#prep data files for relatedness analysis in Demerelate - wild
for(w in 1:length(rel_df_list)) rel_wild_df_list[[w]] <- rel_df_list[[w]][rel_df_list[[w]][,3] == "Wild",-3]

##run relatedness analysis using Demrelate
#use parallel functions
#Calculate the number of cores
cores <- detectCores() - 1
#Initiate cluster
cl <- makeCluster(cores)

#run relatedness analysis for garden and wild pop types 
sp_garden_rel <- parLapply(cl,rel_garden_df_list, Demerelate, tab.dist = "NA", object = TRUE, value = "loiselle")
sp_wild_rel <- parLapply(cl,rel_wild_df_list, Demerelate, tab.dist = "NA", object = TRUE, value = "loiselle")

#matrix to store relatedness results
sp_garden_rel_df <- matrix(nrow = 2, ncol = length(sp_garden_rel))
sp_wild_rel_df <- matrix(nrow = 2, ncol = length(sp_wild_rel))

##Garden demerelate analysis
#create lists 
sp_deme_garden_halfsib_list <- list()
sp_deme_garden_fullsib_list <- list()
sp_deme_garden_halfsib_per_list <- list()
sp_deme_garden_fullsib_per_list <- list()

#loop to calculate demerelate halfsibs and full sibs in gardens 
for(g in 1:length(sp_garden_rel)){
  
  #calculate list of individuals with a half sib in the sample
  sp_deme_garden_rel_df <- as.data.frame(sp_garden_rel[[g]]$Empirical_Relatedness$Garden) 
  
  sp_deme_garden_rel_df$halfsib <- NA
  sp_deme_garden_rel_df$fullsib <- NA
  
  #calculate half-sib levels 
  sp_deme_garden_rel_df$halfsib <- sp_deme_garden_rel_df[,1] > 0.125
  
  #calculate full sib levels 
  sp_deme_garden_rel_df$fullsib <- sp_deme_garden_rel_df[,1] > 0.25
  
  #create a column for individual names 
  sp_deme_garden_rel_df$Ind1 <- gsub("_.*","", rownames(sp_deme_garden_rel_df))
  sp_deme_garden_rel_df$Ind2 <- gsub("^.*\\_","", rownames(sp_deme_garden_rel_df))
  
  #create a list of numbers of individuals with a half or full sib in the sample
  sp_deme_garden_halfsib_list[[g]] <- length(unique(sp_deme_garden_rel_df[sp_deme_garden_rel_df$halfsib == TRUE,]$Ind1))
  sp_deme_garden_fullsib_list[[g]] <- length(unique(sp_deme_garden_rel_df[sp_deme_garden_rel_df$fullsib == TRUE,]$Ind1))
  
  
  #create a list of the percent of individuals with a half or full sib in the sample
  sp_deme_garden_halfsib_per_list[[g]] <- (length(unique(sp_deme_garden_rel_df[sp_deme_garden_rel_df$halfsib == TRUE,]$Ind1))/length(rel_garden_df_list[[g]][rel_garden_df_list[[g]]$Garden_Wild == "Garden",][,1]))*100
  sp_deme_garden_fullsib_per_list[[g]] <- (length(unique(sp_deme_garden_rel_df[sp_deme_garden_rel_df$fullsib == TRUE,]$Ind1))/length(rel_garden_df_list[[g]][rel_garden_df_list[[g]]$Garden_Wild == "Garden",][,1]))*100
  
}

#code for reporting these stats 
#create output matrix
sp_garden_deme_output_df <- matrix(nrow = 2, ncol = length(sp_deme_garden_halfsib_list))

#loop to make the data frame
for(sp in 1:length(sp_deme_garden_halfsib_per_list)){
  
  #half sibling row with % half sibs and # of individuals with a half sib
  sp_garden_deme_output_df[1,sp] <- paste0(signif(as.numeric(sp_deme_garden_halfsib_per_list[[sp]]), 3), "% (", sp_deme_garden_halfsib_list[[sp]], ")")
  
  #full sib percent and number 
  sp_garden_deme_output_df[2,sp] <- paste0(signif(as.numeric(sp_deme_garden_fullsib_per_list[[sp]]), 3), "% (", sp_deme_garden_fullsib_list[[sp]], ")")
  
}

#name rows and columns 
rownames(sp_garden_deme_output_df) <- c("half_sibs","full_sibs")
colnames(sp_garden_deme_output_df) <- scenario_list
#write out data frame 
write.csv(sp_garden_deme_output_df, "../Analyses/Results/Relatedness/sp_garden_deme_output_df.csv")

##Wild demerelate relatedness analysis

#create lists
sp_deme_wild_rel_df <- list()
sp_deme_wild_halfsib_list <- list()
sp_deme_wild_fullsib_list <- list()
sp_deme_wild_halfsib_per_list <- list()
sp_deme_wild_fullsib_per_list <- list()

#loop to calculate demerelate half and full sibs in wild pops 
for(w in 1:length(sp_wild_rel)){
  
  #create data frame 
  sp_deme_wild_df <- sp_wild_rel[[w]]
  
  #create a variable for the # of wild pops 
  sp_wild_pop_num <- length(sp_wild_rel[[w]]$Empirical_Relatedness)
  
  #save relatedness results as data frames
  for(rel in 1:sp_wild_pop_num){
    
    sp_deme_wild_rel_df[[rel]] <- as.data.frame(sp_deme_wild_df$Empirical_Relatedness[rel])
    
    #name column to allow for rbind to work 
    colnames(sp_deme_wild_rel_df[[rel]]) <- c("Rel_Coeff")
  }
  
  #bind data frames together 
  sp_deme_allwildpop_df <- do.call(rbind,sp_deme_wild_rel_df)
  
  #create column for storing relatedness info 
  sp_deme_allwildpop_df$halfsib <- NA
  sp_deme_allwildpop_df$fullsib <- NA
  
  #mark what are not halfsibs 
  sp_deme_allwildpop_df$halfsib <- sp_deme_allwildpop_df[,1] > 0.125
  
  #mark full sibs 
  sp_deme_allwildpop_df$fullsib <- sp_deme_allwildpop_df[,1] > 0.25
  
  #create a column for individual names 
  sp_deme_allwildpop_df$Ind1 <- gsub("_.*","", rownames(sp_deme_allwildpop_df))
  sp_deme_allwildpop_df$Ind2 <- gsub("^.*\\_","", rownames(sp_deme_allwildpop_df))
  
  #create a list of numbers of individuals with a half or full sib in the sample
  sp_deme_wild_halfsib_list[[w]] <- length(unique(sp_deme_allwildpop_df[sp_deme_allwildpop_df$halfsib == TRUE,]$Ind1))
  v[[w]] <- length(unique(sp_deme_allwildpop_df[sp_deme_allwildpop_df$fullsib == TRUE,]$Ind1))
  
  
  #create a list of the percent of individuals with a half or full sib in the sample
  sp_deme_wild_halfsib_per_list[[w]] <- (length(unique(sp_deme_allwildpop_df[sp_deme_allwildpop_df$halfsib == TRUE,]$Ind1))/length(rel_wild_df_list[[w]][,1]))*100
  sp_deme_wild_fullsib_per_list[[w]] <- (length(unique(sp_deme_allwildpop_df[sp_deme_allwildpop_df$fullsib == TRUE,]$Ind1))/length(rel_wild_df_list[[w]][,1]))*100
  
}

##code for reporting these stats 
#create output matrix
sp_wild_deme_output_df <- matrix(nrow = 2, ncol = length(sp_deme_wild_halfsib_list))

#loop to make the data frame
for(sp in 1:length(sp_deme_wild_halfsib_list)){
  
  #half sibling row with % half sibs and # of individuals with a half sib
  sp_wild_deme_output_df[1,sp] <- paste0(signif(as.numeric(sp_deme_wild_halfsib_per_list[[sp]]), 3), "% (", sp_deme_wild_halfsib_list[[sp]], ")")
  
  #full sib percent and number 
  sp_wild_deme_output_df[2,sp] <- paste0(signif(as.numeric(sp_deme_wild_fullsib_per_list[[sp]]), 3), "% (", sp_deme_wild_fullsib_list[[sp]], ")")
  
}

#name rows and columns 
rownames(sp_wild_deme_output_df) <- c("half_sibs", "full_sibs")
colnames(sp_wild_deme_output_df) <- scenario_list

#write out results
write.csv(sp_wild_deme_output_df, "../Analyses/Results/Relatedness/sp_wild_deme_output_df.csv")

###############################
#     Spagedi relatedness     #
###############################

#create list to stores results 
sp_halfsib_list <- list()
sp_fullsib_list <- list()

sp_halfsib_percent_list <- list()
sp_fullsib_percent_list <- list()

#now use a loop to output the number of related ind 
for(rel in 1:length(spagedi_df)){
  
  #first, read in CSV files 
  sp_df <- read.csv(paste0("../Analyses/Results/Relatedness/",spagedi_df[[rel]]))
  
  #next, for each data frame, remove the row with the text "inbreeding coef"
  #this is a line that compares each ind to itself
  sp_df2 <- sp_df[!(sp_df$Dist == "inbreeding coef"),]
  
  ##add columns for sibling levels 
  #half-sib
  sp_df2$half_sib <- NA
  sp_df2$full_sib <- NA
  
  #calculate half-sib levels 
  sp_df2$halfsib <- sp_df2$Rel_Coeff > 0.125
  
  #calculate full sib levels 
  sp_df2$fullsib <- sp_df2$Rel_Coeff > 0.25
  
  #create a list of the percent of individuals with a half or full sib in the sample
  sp_halfsib_list[[rel]] <- length(unique(sp_df2[sp_df2$halfsib == TRUE,][,1]))
  sp_fullsib_list[[rel]] <- length(unique(sp_df2[sp_df2$fullsib == TRUE,][,1]))
  
  #create a list of the percent of individuals with a half or full sib in the sample
  sp_halfsib_percent_list[[rel]] <- (length(unique(sp_df2[sp_df2$halfsib == TRUE,][,1]))/pop_numbers[[rel]])*100
  sp_fullsib_percent_list[[rel]] <- (length(unique(sp_df2[sp_df2$fullsib == TRUE,][,1]))/pop_numbers[[rel]])*100
  
  
}

##code for reporting these stats 
#create output matrix
sp_spagedi_output_df <- matrix(nrow = 2, ncol = length(sp_halfsib_list))

#loop to make the data frame
for(sp in 1:length(sp_halfsib_percent_list)){
  
  #half sibling row with % half sibs and # of individuals with a half sib
  sp_spagedi_output_df[1,sp] <- paste0(signif(as.numeric(sp_halfsib_percent_list[[sp]]), 3), "% (", sp_halfsib_list[[sp]], ")")
  
  #full sib percent and number 
  sp_spagedi_output_df[2,sp] <- paste0(signif(as.numeric(sp_fullsib_percent_list[[sp]]), 3), "% (", sp_fullsib_list[[sp]], ")")
  
}

#name rows and columns 
colnames(sp_spagedi_output_df) <- c("QUAC_garden_sample", "QUAC_garden_whole", "QUAC_wild_sample",
                          "QUAC_wild_whole", "ZAIN_garden_sample", "ZAIN_garden_whole",
                          "ZAIN_wild_sample", "ZAIN_wild_whole")

rownames(sp_spagedi_output_df) <- c("half_sibs","full_sibs")

#write out data file
write.csv(sp_spagedi_output_df, "../Analyses/Results/Relatedness/sp_spagedi_output_df.csv")

sessionInfo()

