##This code is used to generate PCAs for QUAC clustering analysis
#This code uses data frames that have been generated by relatedness reduction -
#where individuals that are related by 25% are reduced to 1 representative 
#individual as this can bias genetic clustering analyses. This analysis
#performs PCAs with several population combinations - all wild pops,
#wild pops with all garden individuals, and finally wild and garden populations
#grouped just by pop types to assess how individuals clustered.

#####################
#     Libraries     #
#####################

library(adegenet)
library(diveRsity)
library(ggplot2)

#########################
#     Load in Files     #
#########################
#set working directory
setwd("../../Data_Files")

#data file lists 
sp_genepop_list <- list.files(path = "Adegenet_Files", pattern = "clean.gen")
sp_df_list <- list.files(path = "Data_Frames", pattern = "clean_df.csv")
species_list <- c("QUAC_wK", "QUAC_woK", "ZAIN_og", "ZAIN_rebinned")
PCA_type <- c("wild_only","garden_wild","garden_allwildpop")

###############
#     PCA     #
###############

#loop to write PCAs for this species 
for(sp in 1:length(species_list)){
  
  #read in genepop files as a genind object
  sp_genind <- read.genepop(paste0("Adegenet_Files/",sp_genepop_list[[1]]), ncode = 3)
  
  #read in data frame 
  sp_df <- read.csv(paste0("Data_Frames/", sp_df_list[[1]]))
  
  #name rows in the genind object 
  rownames(sp_genind@tab) <- sp_df[,1]
  #name pops
  levels(sp_genind@pop) <- unique(sp_df$Pop)
  
  for(p_type in 1:length(PCA_type)){
  
    if(p_type == 1){
    
    #limit data frame by wild populations 
    sp_PCA_df <- sp_df[sp_df$Garden_Wild == "Wild",]
    
    #limit genind object by only wild populations 
    sp_PCA_genind <- sp_genind[rownames(sp_genind@tab) %in% sp_wild_df[,1],]
    
    }
    
    if(p_type == 2){
      
      #limit data frame by wild populations 
      sp_PCA_df <- sp_df[sp_df$Garden_Wild == "Wild",]
      
      
    }
    
    #create tab object for genind 
    sp_tab <- tab(sp_wild_genind, freq=TRUE, NA.method="mean")
  
    #run PCA
    sp_PCA <- dudi.pca(sp_tab, scale = FALSE, nf = 2, scannf = FALSE)
  
    #create PCA data frame 
    sp_PCA_df_temp <- as.data.frame(cbind(as.numeric(sp_PCA$li$Axis1), 
                                       as.numeric(sp_PCA$li$Axis2), 
                                      sp_df$Pop))
  colnames(sp_PCA_df_temp) <- c("Axis1","Axis2","Pop")
  
  #calculate % variation explained by axis 
  sp_pc1 <- signif(((sp_PCA$eig[1])/sum(sp_PCA$eig))*100, 3)
  sp_pc2 <- signif(((sp_PCA$eig[2])/sum(sp_PCA$eig))*100, 3)
  
  #plot PCA
  pdf(paste0("../Analyses/Results/Clustering/", species_list[[sp]], "_allpop_PCA.pdf"),width = 10, height = 8)
  
  print(ggplot(sp_PCA_df_temp, aes(as.numeric(Axis1), as.numeric(Axis2), col = Pop)) + geom_point() + 
          scale_x_continuous(limits = c(min(as.numeric(sp_PCA_df_temp[,1])), max(as.numeric(sp_PCA_df_temp[,1])))) + 
          scale_y_continuous(limits = c(min(as.numeric(sp_PCA_df_temp[,2])), max(as.numeric(sp_PCA_df_temp[,2])))) + 
          xlab(paste0("PC1 (", sp_pc1, "%)")) +
          ylab(paste0("PC2 (", sp_pc2, "%)")) + 
          theme_bw() +  
          scale_color_manual(values=hcl.colors(n = length(unique(sp_PCA_df_temp$Pop)), palette = "viridis")))
  dev.off()
  
  }
}




